env:
  - GO111MODULE=on
  # - GOPROXY=https://gocenter.io
before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - amd64
  ldflags:
    - -s -w -X "main.Version={{ .Tag }}"
  main: "./cmd/domain-harvester/main.go"
dockers:
- goos: linux
  goarch: amd64
  binaries:
    - domain-harvester
  image_templates:
    - "shurshun/{{.ProjectName}}:{{ .Tag }}"
    - "shurshun/{{.ProjectName}}:latest"
  build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=com.github.actions.name={{.ProjectName}}"
    - "--label=com.github.actions.description=Collect domains from all ingress resources in the kubernetes cluster"
    - "--label=com.github.actions.icon=terminal"
    - "--label=com.github.actions.color=blue"
    - "--label=repository=http://github.com/shurshun/{{.ProjectName}}"
    - "--label=maintainer=Korviakov Andrey <korvyakov.a.m@gmail.com>"
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: binary
    replacements:
      amd64: x86_64
source:
  enabled: false
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
